import { test, expect, type Page } from '@playwright/test'

const password = 'synthetic-ui-admin-password'
const memberPassword = 'synthetic-ui-member-password'

async function signIn(page: Page, username: string, secret: string) {
  await page.goto('/login')
  await page.getByLabel('Username', { exact: true }).fill(username)
  await page.getByLabel('Password', { exact: true }).fill(secret)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
}

test('setup, lake configuration, booking snapshots, cancellation, settings, and member isolation', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  const outbound: string[] = []
  page.on('request', request => { if (!request.url().startsWith('http://127.0.0.1:18092/')) outbound.push(request.url()) })

  await test.step('first-run setup uses the API session and renders the embedded build identity', async () => {
    await page.goto('/')
    await expect(page).toHaveURL(/\/setup$/)
    await page.getByLabel('One-time setup token').fill('A'.repeat(43))
    await page.getByLabel('Username', { exact: true }).fill('demo-admin')
    await page.getByLabel('Password', { exact: true }).fill(password)
    await page.getByLabel('Confirm password', { exact: true }).fill(password)
    await page.getByRole('button', { name: 'Create administrator' }).click()
    await expect(page).toHaveURL(/\/lakes$/)
    await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible()
    await expect(page.locator('#build-info')).toHaveAttribute('data-version', 'dev')
    await expect(page.locator('#build-info')).toContainText('Development build')
    const cookies = await page.context().cookies()
    for (const name of ['lake_pass_session', 'lake_pass_csrf']) {
      expect(cookies.find(cookie => cookie.name === name)).toMatchObject({ httpOnly: true, sameSite: 'Strict' })
    }
    expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
  })

  await test.step('configure an inbox and lake while keeping saved credentials hidden', async () => {
    await page.goto('/lakes/buntzen')
    await page.reload()
    await expect(page.getByRole('heading', { name: 'Set up login codes first' })).toBeVisible()
    await page.getByRole('link', { name: 'Set up OTP source' }).click()
    await page.getByRole('link', { name: 'New OTP source', exact: true }).first().click()
    await page.getByLabel('Provider', { exact: true }).selectOption('twilio')
    await expect(page.getByLabel('Server URL')).toBeHidden()
    await expect(page.getByLabel('Server URL')).toBeDisabled()
    await page.getByLabel('Source name').fill('Demo inbox')
    await page.getByLabel('Receiving number').fill('+15550100123')
    await page.getByLabel('Account SID').fill('ACsynthetic-ui-account')
    await page.getByLabel('Auth token').fill('synthetic-ui-provider-secret')
    await page.getByRole('button', { name: 'Create source' }).click()
    await expect(page).toHaveURL(/\/sources\?ok=created$/)
    await expect(page.getByText('Default', { exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Edit', exact: true }).click()
    await expect(page.getByLabel('Auth token')).toHaveValue('')
    await expect(page.getByLabel('Account SID')).toHaveValue('')
    await page.goto('/lakes/buntzen')
    await page.getByRole('link', { name: 'Add Yodel account', exact: true }).click()
    await page.getByLabel('Sign-in name').fill('Demo lake account')
    await page.getByLabel('Mobile phone number').fill('5559876543')
    await page.getByRole('button', { name: 'Save sign-in' }).click()
    await expect(page).toHaveURL(/\/lakes\/buntzen\?ok=created#connection$/)
    await expect(page.getByRole('button', { name: 'Sign in to Yodel', exact: true })).toBeVisible()
    await page.getByLabel('Vehicle keyword').fill('DEMO CAR')
    await page.getByRole('button', { name: 'Save lake defaults' }).click()
    await expect(page.getByText('Personal defaults', { exact: true })).toBeVisible()
  })

  let firstJob = ''
  await test.step('validation preserves the date and pass draft; Book opens one durable job', async () => {
    await page.goto('/bookings/new?lake_id=buntzen')
    await page.getByLabel('Visit date').fill('2030-07-14')
    await page.getByLabel('First choice').selectOption('morning')
    await page.getByLabel('Second choice').selectOption('all_day')
    await page.getByLabel('Third choice').selectOption('')
    await page.getByRole('heading', { name: 'Book Buntzen Lake', exact: true }).click()
    await page.screenshot({ path: info.outputPath('booking.jpg'), type: 'jpeg', quality: 88, fullPage: true })
    await page.getByLabel('Second choice').selectOption('morning')
    await page.getByRole('button', { name: 'Book', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('only be selected once')
    await expect(page.getByRole('alert')).toBeFocused()
    await expect(page.getByLabel('Visit date')).toHaveValue('2030-07-14')
    await expect(page.getByLabel('Second choice')).toHaveValue('morning')
    await page.getByLabel('Second choice').selectOption('all_day')
    await page.getByLabel('Third choice').selectOption('')
    await page.getByRole('button', { name: 'Book', exact: true }).click()
    await expect(page).toHaveURL(/\/jobs\/\d+\?ok=queued$/)
    firstJob = new URL(page.url()).pathname
    await expect(page.getByText('Connected · live updates.', { exact: true })).toBeVisible()
    await expect(page.getByText('2030-07-14 · America/Vancouver')).toBeVisible()
    await expect(page.getByText('DEMO CAR', { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Cancel job', exact: true })).toBeEnabled()
    await page.reload()
    await expect(page.getByText('2030-07-14 · America/Vancouver')).toBeVisible()
    await page.getByRole('button', { name: 'Cancel job', exact: true }).click()
    // The server drains final durable events for up to two polling intervals.
    await expect(page.getByText('Completed · live updates ended.', { exact: true })).toBeVisible({ timeout: 10_000 })
    await expect(page.getByRole('button', { name: 'Cancel job', exact: true })).toHaveCount(0)
    await page.goto('/jobs')
    await expect(page.getByRole('row')).toHaveCount(2)
    await expect(page.getByRole('table')).toContainText('cancelled')
  })

  await test.step('changed preferences affect the next visit; history and mobile navigation remain usable', async () => {
    await page.goto('/lakes/buntzen')
    await page.getByLabel('Vehicle keyword').fill('NEXT DEMO CAR')
    await page.getByRole('button', { name: 'Save lake defaults' }).click()
    await expect(page.getByText('Changes saved.', { exact: true })).toBeVisible()
    await page.goto(firstJob)
    await expect(page.getByText('DEMO CAR', { exact: true })).toBeVisible()
    await expect(page.getByText('NEXT DEMO CAR', { exact: true })).toHaveCount(0)
    await page.goto('/bookings/new?lake_id=buntzen')
    await page.getByLabel('Visit date').fill('2030-07-15')
    await page.getByRole('button', { name: 'Book', exact: true }).click()
    await expect(page).toHaveURL(/\/jobs\/\d+\?ok=queued$/)
    await expect(page.getByText('NEXT DEMO CAR', { exact: true })).toBeVisible()
    await page.goto('/jobs')
    await expect(page.getByRole('row')).toHaveCount(3)
    expect(await page.getByRole('region', { name: 'Job history' }).evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath('jobs.jpg'), type: 'jpeg', quality: 88, fullPage: true })
    await page.goto('/')
    await expect(page.getByText('1 upcoming visit', { exact: true })).toBeVisible()
    await page.screenshot({ path: info.outputPath('workspace.jpg'), type: 'jpeg', quality: 88, fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeHidden()
    await page.getByRole('button', { name: 'Toggle navigation' }).click()
    await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeHidden()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath('mobile.png'), fullPage: true })
    await page.setViewportSize({ width: 1280, height: 900 })
  })

  await test.step('network settings save, reload and retain their current host', async () => {
    await page.goto('/settings/network')
    await page.getByLabel('Allowed hostnames', { exact: true }).fill('127.0.0.1:18092')
    await page.getByRole('switch').check()
    await page.getByRole('button', { name: 'Save network settings' }).click()
    await expect(page).toHaveURL(/\/settings\/network\?ok=updated$/)
    await page.reload()
    await expect(page.getByRole('switch')).toBeChecked()
    await page.getByRole('switch').uncheck()
    await page.getByRole('button', { name: 'Save network settings' }).click()
    await expect(page.getByText('Changes saved.', { exact: true })).toBeVisible()
  })

  await test.step('temporary passwords and account boundaries survive the client migration', async () => {
    await page.goto('/admin/users/new')
    await page.getByLabel('Username', { exact: true }).fill('demo-member')
    await page.getByLabel('Temporary password', { exact: true }).fill(memberPassword)
    await page.getByLabel('Confirm temporary password', { exact: true }).fill(memberPassword)
    await page.getByRole('button', { name: 'Create user', exact: true }).click()
    await expect(page).toHaveURL(/\/admin\/users\?ok=user-created$/)
    await page.getByRole('button', { name: 'Sign out', exact: true }).click()
    await expect(page).toHaveURL(/\/login$/)
    await signIn(page, 'demo-member', memberPassword)
    await expect(page).toHaveURL(/\/account\?password=required$/)
    await expect(page.getByRole('button', { name: 'Change username', exact: true })).toHaveCount(0)
    await page.getByLabel('Current password', { exact: true }).fill(memberPassword)
    await page.getByLabel('New password', { exact: true }).fill('synthetic-ui-member-replacement')
    await page.getByLabel('Confirm new password', { exact: true }).fill('synthetic-ui-member-replacement')
    await page.getByRole('button', { name: 'Change password', exact: true }).click()
    await expect(page).toHaveURL(/\/login\?ok=password-changed$/)
    await signIn(page, 'demo-member', 'synthetic-ui-member-replacement')
    await expect(page).toHaveURL(/\/lakes$/)
    await page.goto('/settings')
    await expect(page.getByRole('link', { name: 'Network', exact: true })).toHaveCount(0)
    await expect(page.getByRole('link', { name: 'Users', exact: true })).toHaveCount(0)
    await page.goto(firstJob)
    await expect(page.getByRole('heading', { name: 'Page not found', exact: true })).toBeVisible()
    await expect(page.getByText('Demo lake account')).toHaveCount(0)
    await page.goto('/admin/users')
    await expect(page.getByRole('heading', { name: "That action isn't available", exact: true })).toBeVisible()
  })
  expect(outbound).toEqual([])
  // Expected 403/404 resource messages are reported by Chromium's network console.
  expect(errors.filter(message => !/Failed to load resource: the server responded with a status of (403|404|422)/.test(message))).toEqual([])
})
